/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.infrastructure

import com.squareup.moshi.JsonDataException
import com.squareup.moshi.Moshi
import retrofit2.Response

@Throws(JsonDataException::class)
inline fun <reified T> Response<*>.getErrorResponse(serializerBuilder: Moshi.Builder = Serializer.moshiBuilder): T? {
    val serializer = serializerBuilder.build()
    val parser = serializer.adapter(T::class.java)
    val response = errorBody()?.string()
    if (response != null) {
        return parser.fromJson(response)
    }
    return null
}
