/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.apis

import remote.infrastructure.CollectionFormats.*
import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json

import remote.models.LoginRequest
import remote.models.Relationship
import remote.models.User

import okhttp3.MultipartBody

interface UsersApi {
    /**
     * POST users
     * Creating an user
     * 
     * Responses:
     *  - 201: Created
     *  - 400: Bad Request
     *  - 500: Internal Server Error
     *
     * @param loginRequest 
     * @return [User]
     */
    @POST("users")
    suspend fun addUser(@Body loginRequest: LoginRequest): Response<User>

    /**
     * GET users/{username}/followers
     * Getting an user&#39;s followers
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username Username of user to follow
     * @param offset 0-indexed offset of the first follower to return (optional)
     * @param limit Maximum number of followings to get (Default 40, Max 80) (optional)
     * @return [kotlin.collections.List<User>]
     */
    @GET("users/{username}/followers")
    suspend fun findFollowers(@Path("username") username: kotlin.String, @Query("offset") offset: kotlin.Int? = null, @Query("limit") limit: kotlin.Int? = null): Response<kotlin.collections.List<User>>

    /**
     * GET users/{username}/following
     * Getting who user is following
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username Username of user to follow
     * @param offset 0-indexed offset of the first following user to return (optional)
     * @param limit Maximum number of followings to get (Default 40, Max 80) (optional)
     * @return [kotlin.collections.List<User>]
     */
    @GET("users/{username}/following")
    suspend fun findFollowing(@Path("username") username: kotlin.String, @Query("offset") offset: kotlin.Int? = null, @Query("limit") limit: kotlin.Int? = null): Response<kotlin.collections.List<User>>

    /**
     * GET users/relationships
     * Getting an user&#39;s relationships
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 401: Unauthorized
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username User Usernames (Username Must be Separated by Comma)
     * @return [kotlin.collections.List<Relationship>]
     */
    @GET("users/relationships")
    suspend fun findRelationships(@Query("username") username: kotlin.String): Response<kotlin.collections.List<Relationship>>

    /**
     * GET users/{username}
     * Fetching an user
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username Username of user to return
     * @return [User]
     */
    @GET("users/{username}")
    suspend fun findUserByUsername(@Path("username") username: kotlin.String): Response<User>

    /**
     * POST users/{username}/follow
     * Following an user
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 401: Unauthorized
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username Username of user to follow
     * @return [Relationship]
     */
    @POST("users/{username}/follow")
    suspend fun followUser(@Path("username") username: kotlin.String): Response<Relationship>

    /**
     * POST users/{username}/unfollow
     * Unfollowing an user
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 401: Unauthorized
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param username Username of user to follow
     * @return [Relationship]
     */
    @POST("users/{username}/unfollow")
    suspend fun unfollowUser(@Path("username") username: kotlin.String): Response<Relationship>

    /**
     * POST users/update_credentials
     * Updating an user
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 401: Unauthorized
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param displayName The name to display in the user&#39;s profile   (optional)
     * @param note A new biography for the user (optional)
     * @param avatar An avatar for the user (encoded using multipart/form-data) (optional)
     * @param header A header image for the user (encoded using multipart/form-data) (optional)
     * @return [User]
     */
    @Multipart
    @POST("users/update_credentials")
    suspend fun updateUser(@Part("display_name") displayName: kotlin.String? = null, @Part("note") note: kotlin.String? = null, @Part avatar: MultipartBody.Part? = null, @Part header: MultipartBody.Part? = null): Response<User>

}
