/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.apis

import remote.infrastructure.CollectionFormats.*
import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json

import remote.models.AddYweetRequest
import remote.models.Yweet

interface YweetsApi {
    /**
     * POST yweets
     * Posting a new yweet
     * 
     * Responses:
     *  - 201: Created
     *  - 400: Bad Request
     *  - 401: Unauthorized
     *  - 500: Internal Server Error
     *
     * @param addYweetRequest 
     * @return [Yweet]
     */
    @POST("yweets")
    suspend fun addYweet(@Body addYweetRequest: AddYweetRequest): Response<Yweet>

    /**
     * DELETE yweets/{id}
     * Deleting a yweet
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param id ID of Yweet to delete
     * @return [kotlin.Any]
     */
    @DELETE("yweets/{id}")
    suspend fun deleteYweet(@Path("id") id: kotlin.Int): Response<kotlin.Any>

    /**
     * GET yweets/{id}
     * Fetching an yweet
     * 
     * Responses:
     *  - 200: OK
     *  - 400: Bad Request
     *  - 404: Resource Not Found
     *  - 500: Internal Server Error
     *
     * @param id ID of Yweet to return
     * @return [Yweet]
     */
    @GET("yweets/{id}")
    suspend fun findYweetByID(@Path("id") id: kotlin.Int): Response<Yweet>

}
