/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.models

import remote.models.AttachmentRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param yweet The text of the yweet
 * @param images 
 */
@JsonClass(generateAdapter = true)
data class AddYweetRequest (
    /* The text of the yweet */
    @Json(name = "yweet")
    val yweet: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<AttachmentRequest>? = null

) {


}

