/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id ID of the attachment
 * @param type One of: \"image\", \"video\", \"gifv\", \"unknown\"
 * @param url URL of the image
 * @param description A description of the image for the visually impaired (maximum 420 characters), or `null` if none provided
 */
@JsonClass(generateAdapter = true)
data class Attachment (
    /* ID of the attachment */
    @Json(name = "id")
    val id: kotlin.Int,

    /* One of: \"image\", \"video\", \"gifv\", \"unknown\" */
    @Json(name = "type")
    val type: kotlin.String,

    /* URL of the image */
    @Json(name = "url")
    val url: kotlin.String,

    /* A description of the image for the visually impaired (maximum 420 characters), or `null` if none provided */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

