/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Target user id
 * @param following Whether the user is currently following the user
 * @param followedBy Whether the user is currently being followed by the user
 */
@JsonClass(generateAdapter = true)
data class Relationship (
    /* Target user id */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Whether the user is currently following the user */
    @Json(name = "following")
    val following: kotlin.Boolean,

    /* Whether the user is currently being followed by the user */
    @Json(name = "followed_by")
    val followedBy: kotlin.Boolean

) {


}

