/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "DuplicatedCode",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "RemoveRedundantCallsOfConversionMethods",
  "REDUNDANT_CALL_OF_CONVERSION_METHOD",
  "RedundantUnitReturnType",
  "RemoveEmptyClassBody",
  "UnnecessaryVariable",
  "UnusedImport",
  "UnnecessaryVariable",
  "unused",
  "ProtectedInFinal",
  "AddExplicitTargetToParameterAnnotation",
)
package remote.models

import remote.models.Attachment
import remote.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The ID of the yweet
 * @param user 
 * @param content Body of the yweet; this will contain HTML (remote HTML already sanitized)
 * @param createdAt The time the yweet was created
 * @param imageAttachments 
 */
@JsonClass(generateAdapter = true)
data class Yweet (
    /* The ID of the yweet */
    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "user")
    val user: User,

    /* Body of the yweet; this will contain HTML (remote HTML already sanitized) */
    @Json(name = "content")
    val content: kotlin.String,

    /* The time the yweet was created */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "image_attachments")
    val imageAttachments: kotlin.collections.List<Attachment>

) {


}

